// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gacha.proto

package gacha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawRequest) Reset() {
	*x = DrawRequest{}
	mi := &file_proto_gacha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawRequest) ProtoMessage() {}

func (x *DrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawRequest.ProtoReflect.Descriptor instead.
func (*DrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{0}
}

func (x *DrawRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=itemName,proto3" json:"itemName,omitempty"`
	Rarity        string                 `protobuf:"bytes,2,opt,name=rarity,proto3" json:"rarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawResponse) Reset() {
	*x = DrawResponse{}
	mi := &file_proto_gacha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawResponse) ProtoMessage() {}

func (x *DrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawResponse.ProtoReflect.Descriptor instead.
func (*DrawResponse) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{1}
}

func (x *DrawResponse) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *DrawResponse) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

type GachaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GachaType     string                 `protobuf:"bytes,1,opt,name=gachaType,proto3" json:"gachaType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaRequest) Reset() {
	*x = GachaRequest{}
	mi := &file_proto_gacha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaRequest) ProtoMessage() {}

func (x *GachaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaRequest.ProtoReflect.Descriptor instead.
func (*GachaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{2}
}

func (x *GachaRequest) GetGachaType() string {
	if x != nil {
		return x.GachaType
	}
	return ""
}

type GachaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GachaCateg    string                 `protobuf:"bytes,1,opt,name=gachaCateg,proto3" json:"gachaCateg,omitempty"`
	Remaining     string                 `protobuf:"bytes,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=endDate,proto3" json:"endDate,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,5,opt,name=ownerUserId,proto3" json:"ownerUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaResponse) Reset() {
	*x = GachaResponse{}
	mi := &file_proto_gacha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaResponse) ProtoMessage() {}

func (x *GachaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaResponse.ProtoReflect.Descriptor instead.
func (*GachaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{3}
}

func (x *GachaResponse) GetGachaCateg() string {
	if x != nil {
		return x.GachaCateg
	}
	return ""
}

func (x *GachaResponse) GetRemaining() string {
	if x != nil {
		return x.Remaining
	}
	return ""
}

func (x *GachaResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GachaResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GachaResponse) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

var File_proto_gacha_proto protoreflect.FileDescriptor

const file_proto_gacha_proto_rawDesc = "" +
	"\n" +
	"\x11proto/gacha.proto\x12\x04main\"%\n" +
	"\vDrawRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\fDrawResponse\x12\x1a\n" +
	"\bitemName\x18\x01 \x01(\tR\bitemName\x12\x16\n" +
	"\x06rarity\x18\x02 \x01(\tR\x06rarity\",\n" +
	"\fGachaRequest\x12\x1c\n" +
	"\tgachaType\x18\x01 \x01(\tR\tgachaType\"\xa7\x01\n" +
	"\rGachaResponse\x12\x1e\n" +
	"\n" +
	"gachaCateg\x18\x01 \x01(\tR\n" +
	"gachaCateg\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\tR\tremaining\x12\x1c\n" +
	"\tstartDate\x18\x03 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x04 \x01(\tR\aendDate\x12 \n" +
	"\vownerUserId\x18\x05 \x01(\tR\vownerUserId2v\n" +
	"\fGachaService\x12-\n" +
	"\x04Draw\x12\x11.main.DrawRequest\x1a\x12.main.DrawResponse\x127\n" +
	"\fGetGachaInfo\x12\x12.main.GachaRequest\x1a\x13.main.GachaResponseB\x13Z\x11proto/proto;gachab\x06proto3"

var (
	file_proto_gacha_proto_rawDescOnce sync.Once
	file_proto_gacha_proto_rawDescData []byte
)

func file_proto_gacha_proto_rawDescGZIP() []byte {
	file_proto_gacha_proto_rawDescOnce.Do(func() {
		file_proto_gacha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gacha_proto_rawDesc), len(file_proto_gacha_proto_rawDesc)))
	})
	return file_proto_gacha_proto_rawDescData
}

var file_proto_gacha_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_gacha_proto_goTypes = []any{
	(*DrawRequest)(nil),   // 0: main.DrawRequest
	(*DrawResponse)(nil),  // 1: main.DrawResponse
	(*GachaRequest)(nil),  // 2: main.GachaRequest
	(*GachaResponse)(nil), // 3: main.GachaResponse
}
var file_proto_gacha_proto_depIdxs = []int32{
	0, // 0: main.GachaService.Draw:input_type -> main.DrawRequest
	2, // 1: main.GachaService.GetGachaInfo:input_type -> main.GachaRequest
	1, // 2: main.GachaService.Draw:output_type -> main.DrawResponse
	3, // 3: main.GachaService.GetGachaInfo:output_type -> main.GachaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gacha_proto_init() }
func file_proto_gacha_proto_init() {
	if File_proto_gacha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gacha_proto_rawDesc), len(file_proto_gacha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gacha_proto_goTypes,
		DependencyIndexes: file_proto_gacha_proto_depIdxs,
		MessageInfos:      file_proto_gacha_proto_msgTypes,
	}.Build()
	File_proto_gacha_proto = out.File
	file_proto_gacha_proto_goTypes = nil
	file_proto_gacha_proto_depIdxs = nil
}
