// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gacha.proto

package gachapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GachaId       string                 `protobuf:"bytes,2,opt,name=gachaId,proto3" json:"gachaId,omitempty"`
	DrawAmount    int32                  `protobuf:"varint,3,opt,name=drawAmount,proto3" json:"drawAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawRequest) Reset() {
	*x = DrawRequest{}
	mi := &file_proto_gacha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawRequest) ProtoMessage() {}

func (x *DrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawRequest.ProtoReflect.Descriptor instead.
func (*DrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{0}
}

func (x *DrawRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DrawRequest) GetGachaId() string {
	if x != nil {
		return x.GachaId
	}
	return ""
}

func (x *DrawRequest) GetDrawAmount() int32 {
	if x != nil {
		return x.DrawAmount
	}
	return 0
}

type DrawItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rarity        string                 `protobuf:"bytes,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawItem) Reset() {
	*x = DrawItem{}
	mi := &file_proto_gacha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawItem) ProtoMessage() {}

func (x *DrawItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawItem.ProtoReflect.Descriptor instead.
func (*DrawItem) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{1}
}

func (x *DrawItem) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *DrawItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DrawItem) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

type DrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DrawItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawResponse) Reset() {
	*x = DrawResponse{}
	mi := &file_proto_gacha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawResponse) ProtoMessage() {}

func (x *DrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawResponse.ProtoReflect.Descriptor instead.
func (*DrawResponse) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{2}
}

func (x *DrawResponse) GetItems() []*DrawItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GachaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GachaType     string                 `protobuf:"bytes,1,opt,name=gachaType,proto3" json:"gachaType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaRequest) Reset() {
	*x = GachaRequest{}
	mi := &file_proto_gacha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaRequest) ProtoMessage() {}

func (x *GachaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaRequest.ProtoReflect.Descriptor instead.
func (*GachaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{3}
}

func (x *GachaRequest) GetGachaType() string {
	if x != nil {
		return x.GachaType
	}
	return ""
}

type GacheRarityRemain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rarity        string                 `protobuf:"bytes,1,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GacheRarityRemain) Reset() {
	*x = GacheRarityRemain{}
	mi := &file_proto_gacha_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GacheRarityRemain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GacheRarityRemain) ProtoMessage() {}

func (x *GacheRarityRemain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GacheRarityRemain.ProtoReflect.Descriptor instead.
func (*GacheRarityRemain) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{4}
}

func (x *GacheRarityRemain) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *GacheRarityRemain) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type GachaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RarityInfos   []*GacheRarityRemain   `protobuf:"bytes,2,rep,name=rarityInfos,proto3" json:"rarityInfos,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=endDate,proto3" json:"endDate,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,5,opt,name=ownerUserId,proto3" json:"ownerUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaResponse) Reset() {
	*x = GachaResponse{}
	mi := &file_proto_gacha_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaResponse) ProtoMessage() {}

func (x *GachaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gacha_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaResponse.ProtoReflect.Descriptor instead.
func (*GachaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gacha_proto_rawDescGZIP(), []int{5}
}

func (x *GachaResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GachaResponse) GetRarityInfos() []*GacheRarityRemain {
	if x != nil {
		return x.RarityInfos
	}
	return nil
}

func (x *GachaResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GachaResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GachaResponse) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

var File_proto_gacha_proto protoreflect.FileDescriptor

const file_proto_gacha_proto_rawDesc = "" +
	"\n" +
	"\x11proto/gacha.proto\x12\x04main\"_\n" +
	"\vDrawRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\agachaId\x18\x02 \x01(\tR\agachaId\x12\x1e\n" +
	"\n" +
	"drawAmount\x18\x03 \x01(\x05R\n" +
	"drawAmount\"L\n" +
	"\bDrawItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06rarity\x18\x03 \x01(\tR\x06rarity\"4\n" +
	"\fDrawResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.main.DrawItemR\x05items\",\n" +
	"\fGachaRequest\x12\x1c\n" +
	"\tgachaType\x18\x01 \x01(\tR\tgachaType\"I\n" +
	"\x11GacheRarityRemain\x12\x16\n" +
	"\x06rarity\x18\x01 \x01(\tR\x06rarity\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\"\xb8\x01\n" +
	"\rGachaResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\vrarityInfos\x18\x02 \x03(\v2\x17.main.GacheRarityRemainR\vrarityInfos\x12\x1c\n" +
	"\tstartDate\x18\x03 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x04 \x01(\tR\aendDate\x12 \n" +
	"\vownerUserId\x18\x05 \x01(\tR\vownerUserId2v\n" +
	"\fGachaService\x12-\n" +
	"\x04Draw\x12\x11.main.DrawRequest\x1a\x12.main.DrawResponse\x127\n" +
	"\fGetGachaInfo\x12\x12.main.GachaRequest\x1a\x13.main.GachaResponseB5Z3github.com/inonsdn/gacha-system/proto/gacha;gachapbb\x06proto3"

var (
	file_proto_gacha_proto_rawDescOnce sync.Once
	file_proto_gacha_proto_rawDescData []byte
)

func file_proto_gacha_proto_rawDescGZIP() []byte {
	file_proto_gacha_proto_rawDescOnce.Do(func() {
		file_proto_gacha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gacha_proto_rawDesc), len(file_proto_gacha_proto_rawDesc)))
	})
	return file_proto_gacha_proto_rawDescData
}

var file_proto_gacha_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_gacha_proto_goTypes = []any{
	(*DrawRequest)(nil),       // 0: main.DrawRequest
	(*DrawItem)(nil),          // 1: main.DrawItem
	(*DrawResponse)(nil),      // 2: main.DrawResponse
	(*GachaRequest)(nil),      // 3: main.GachaRequest
	(*GacheRarityRemain)(nil), // 4: main.GacheRarityRemain
	(*GachaResponse)(nil),     // 5: main.GachaResponse
}
var file_proto_gacha_proto_depIdxs = []int32{
	1, // 0: main.DrawResponse.items:type_name -> main.DrawItem
	4, // 1: main.GachaResponse.rarityInfos:type_name -> main.GacheRarityRemain
	0, // 2: main.GachaService.Draw:input_type -> main.DrawRequest
	3, // 3: main.GachaService.GetGachaInfo:input_type -> main.GachaRequest
	2, // 4: main.GachaService.Draw:output_type -> main.DrawResponse
	5, // 5: main.GachaService.GetGachaInfo:output_type -> main.GachaResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_gacha_proto_init() }
func file_proto_gacha_proto_init() {
	if File_proto_gacha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gacha_proto_rawDesc), len(file_proto_gacha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gacha_proto_goTypes,
		DependencyIndexes: file_proto_gacha_proto_depIdxs,
		MessageInfos:      file_proto_gacha_proto_msgTypes,
	}.Build()
	File_proto_gacha_proto = out.File
	file_proto_gacha_proto_goTypes = nil
	file_proto_gacha_proto_depIdxs = nil
}
